services:
  t3code:
    restart: always
    build:
      context: .
      target: runner
    environment:
      CODEX_HOME: /codex-home
    ports:
      - "3773:3773"
    volumes:
      - /Users/wesley/Development:/data
      - /Users/wesley/.codex:/codex-home
      - /var/run/docker.sock:/var/run/docker.sock
